<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://iotmonitoring.com/alarm"
    targetNamespace="http://iotmonitoring.com/alarm"
    name="AlarmService">

    <wsdl:types>
        <xs:schema>
            <xs:import
                namespace="http://iotmonitoring.com/alarm"
                schemaLocation="alarm_v1.xsd"/>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="ProcessMeasurementInput">
        <wsdl:part name="parameters" element="tns:ProcessMeasurementRequest"/>
    </wsdl:message>
    <wsdl:message name="ProcessMeasurementOutput">
        <wsdl:part name="parameters" element="tns:ProcessMeasurementResponse"/>
    </wsdl:message>

    <wsdl:message name="GetAlarmInput">
        <wsdl:part name="parameters" element="tns:GetAlarmRequest"/>
    </wsdl:message>
    <wsdl:message name="GetAlarmOutput">
        <wsdl:part name="parameters" element="tns:GetAlarmResponse"/>
    </wsdl:message>

    <wsdl:message name="GetThresholdInput">
        <wsdl:part name="parameters" element="tns:GetThresholdRequest"/>
    </wsdl:message>
    <wsdl:message name="GetThresholdOutput">
        <wsdl:part name="parameters" element="tns:GetThresholdResponse"/>
    </wsdl:message>

    <wsdl:message name="AlarmFaultMessage">
        <wsdl:part name="fault" element="tns:AlarmFault"/>
    </wsdl:message>

    <wsdl:portType name="AlarmServicePortType">
        <wsdl:operation name="processMeasurement">
            <wsdl:input message="tns:ProcessMeasurementInput"/>
            <wsdl:output message="tns:ProcessMeasurementOutput"/>
            <wsdl:fault name="AlarmFault" message="tns:AlarmFaultMessage"/>
        </wsdl:operation>

        <wsdl:operation name="getAlarm">
            <wsdl:input message="tns:GetAlarmInput"/>
            <wsdl:output message="tns:GetAlarmOutput"/>
            <wsdl:fault name="AlarmFault" message="tns:AlarmFaultMessage"/>
        </wsdl:operation>

        <wsdl:operation name="getThreshold">
            <wsdl:input message="tns:GetThresholdInput"/>
            <wsdl:output message="tns:GetThresholdOutput"/>
            <wsdl:fault name="AlarmFault" message="tns:AlarmFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="AlarmServiceSoapBinding" type="tns:AlarmServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="processMeasurement">
            <soap:operation soapAction="http://iotmonitoring.com/alarm/processMeasurement"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
            <wsdl:fault name="AlarmFault"><soap:fault name="AlarmFault" use="literal"/></wsdl:fault>
        </wsdl:operation>

        <wsdl:operation name="getAlarm">
            <soap:operation soapAction="http://iotmonitoring.com/alarm/getAlarm"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
            <wsdl:fault name="AlarmFault"><soap:fault name="AlarmFault" use="literal"/></wsdl:fault>
        </wsdl:operation>

        <wsdl:operation name="getThreshold">
            <soap:operation soapAction="http://iotmonitoring.com/alarm/getThreshold"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
            <wsdl:fault name="AlarmFault"><soap:fault name="AlarmFault" use="literal"/></wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="AlarmService">
        <wsdl:port name="AlarmServicePort" binding="tns:AlarmServiceSoapBinding">
            <soap:address location="http://localhost:8081/ws/alarm"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
