# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:
# https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - integration-service

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        working-directory: ./services/integration-service
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/services/integration-service/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DC5FA934BEAD40E4919C772E06FE4010 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_54205B4BDBDB479E80C5561231DBF38D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E7926D9694AA45809E215861C65F878E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'integration-service'
          slot-name: 'Production'
          package: '*.jar'
