<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://iotmonitoring.com/alarm" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://iotmonitoring.com/alarm" name="AlarmService">
    <types><xsd:schema><xsd:import namespace="http://iotmonitoring.com/alarm" schemaLocation="alarm-service.xsd"/></xsd:schema></types>
    <message name="ProcessMeasurementRequest"><part name="parameters" element="tns:ProcessMeasurementRequest"/></message><message name="ProcessMeasurementResponse"><part name="parameters" element="tns:ProcessMeasurementResponse"/></message>
    <message name="GetAlarmRequest"><part name="parameters" element="tns:GetAlarmRequest"/></message><message name="GetAlarmResponse"><part name="parameters" element="tns:GetAlarmResponse"/></message>
    <message name="GetThresholdRequest"><part name="parameters" element="tns:GetThresholdRequest"/></message><message name="GetThresholdResponse"><part name="parameters" element="tns:GetThresholdResponse"/></message><message name="AlarmFault"><part name="fault" element="tns:AlarmFault"/></message>
    <portType name="AlarmPort"><operation name="processMeasurement"><input message="tns:ProcessMeasurementRequest"/><output message="tns:ProcessMeasurementResponse"/><fault name="AlarmFault" message="tns:AlarmFault"/></operation><operation name="getAlarm"><input message="tns:GetAlarmRequest"/><output message="tns:GetAlarmResponse"/><fault name="AlarmFault" message="tns:AlarmFault"/></operation><operation name="getThreshold"><input message="tns:GetThresholdRequest"/><output message="tns:GetThresholdResponse"/><fault name="AlarmFault" message="tns:AlarmFault"/></operation></portType>
    <binding name="AlarmSoapBinding" type="tns:AlarmPort"><soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" transport="http://schemas.xmlsoap.org/soap/http"/><operation name="processMeasurement"><soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="processMeasurement"/></operation><operation name="getAlarm"><soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="getAlarm"/></operation><operation name="getThreshold"><soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="getThreshold"/></operation></binding>
    <service name="AlarmService"><port name="AlarmPort" binding="tns:AlarmSoapBinding"><soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://localhost:8083/ws"/></port></service>
</definitions>
